name: C/C++ CI

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Tests
        run: |
          mkdir build && cd build  
          cmake ..
          make all
      - name: Run Tests
        run: 
          $HOME/build/ ctest
      
