name: Build and Test

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Tests
        run: |
          mkdir build && cd build  
          cmake ..
          make all
      - name: Run Tests
        run: |
          cd build
          ctest
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: build-artifacts
          path: build/
